2003/02/09 ver 1.1.4.12 unofficial pre-release
	From Stas
	- $_pic_watchdog related PIC code adjustments.
	From Fran Sabolich <fsabolich@yahoo.com>
	- implement break handling in ser_ports.c (cleaned up by Stas)
	From Bart
	- Enable/disable all plugins via compiletime-settings.
	- By default, only use the supplied S-Lang library if the system
	  supplied S-Lang library does not have the UTF-8 hack.
	- Simplify S-Lang configuration by using DOSEMU's config.h
	- Add 64-bit file locking support.
	- Add $_full_file_locks option to lock whole files instead of just 
	  one (for DOS invisible) byte.
	- Set $_pic_watchdog default to 50 (suggested by Stas).
	- Set $_hdimage default to "drives/*".
	- Use ~/.dosemu for the $_hdimage basedir, falling back to 
	  /var/lib/dosemu if necessary.
	- Use proper long X names for the VGA fonts.
	- Add ability to use a DOS command as a DOSEMU option (without
	  -E). In that case "exitemu" happens automatically when the DOS
	  command terminates.
	- (With help from Reinhard) only apply cleanup_child to the port 
	  server and not to any other children.
	- clean up dosdebug; use dynamic memory allocation, and remove the
	  need for the ~/.dosemu/run/dosemu.<pid> files.
	- temp file cleanup: the "mapfile" mapping driver and printer now
	  use tmpfile(3) to create the temporary file. That way the file
	  is automatically deleted even if DOSEMU crashes, and noone else
	  can open the file. Because of this, the printer code now uses a 
	  pipe to communicate with lpr.
	- DOSEMU is now quiet by default. It now doesn't say it's running
	  in low feature mode, but instead tells you if it's running with
	  root privileges.
	- (suggested by Stas) Use normal local variables instead of
	  statics where possible for the serial code.
	- Fix bug "xms_EMB_info" in XMS code.
	- Set video_ints for vgaemu code, otherwise it will forget about
	  the fonts later.
	- Applied some Debian tweaks from Herbert Xu 
	  * to have DOSEMU working out of the box even if the user doesn't
	    have a private installation.
	  * $_hdimage drives adjust according to the setting of DOSDRIVE_D.
	  * change /etc/dosemu.conf to /etc/dosemu/dosemu.conf to match the
	    default (we still support /etc/dosemu.conf however).
	- Script changes:
	  * adjust to use ~/.dosemu/drives/* by default; ~/.dosemurc is no
	    longer compulsary even for private installations.
	  * do -home by default
	  * only display "what DOSEMU does" once, be quiet afterwards.
	  * apply the '\r' keystroke by default to boot DOS quicker. Just
	    use -input without arguments if you want to use F5 or F8.
	  * use -install without arguments to force a FreeDOS
	    re-installation.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4173,7 +4173,8 @@ fi
 
 
 
-for ac_header in fcntl.h limits.h syslog.h sys/file.h sys/ioctl.h sys/time.h unistd.h
+
+for ac_header in fcntl.h limits.h syslog.h sys/file.h sys/ioctl.h sys/time.h unistd.h termios.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -6242,7 +6243,6 @@ echo "$as_me: WARNING: " >&2;}
 
 
 LDFLAGS="-Wl,-warn-common"
-LIBS=-lm
 
 # Check whether --enable-linkstatic or --disable-linkstatic was given.
 if test "${enable_linkstatic+set}" = set; then
@@ -6469,14 +6469,72 @@ echo $ECHO_N "checking for S-Lang... $ECHO_C" >&6
   fi
     echo "$as_me:$LINENO: result: $SLANGINC $SLANGLIB" >&5
 echo "${ECHO_T}$SLANGINC $SLANGLIB" >&6
+  echo "$as_me:$LINENO: checking for SLsmg_write_nwchars in -lslang" >&5
+echo $ECHO_N "checking for SLsmg_write_nwchars in -lslang... $ECHO_C" >&6
+if test "${ac_cv_lib_slang_SLsmg_write_nwchars+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lslang -lm -ldl $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-echo "$as_me:$LINENO: checking for SLtt_get_terminfo in -lslang" >&5
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SLsmg_write_nwchars ();
+int
+main ()
+{
+SLsmg_write_nwchars ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_slang_SLsmg_write_nwchars=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_slang_SLsmg_write_nwchars=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_slang_SLsmg_write_nwchars" >&5
+echo "${ECHO_T}$ac_cv_lib_slang_SLsmg_write_nwchars" >&6
+if test $ac_cv_lib_slang_SLsmg_write_nwchars = yes; then
+  { echo "$as_me:$LINENO: WARNING: Rejecting system S-Lang with UTF-8 support. It is incompatible with DOSEMU. Using supplied S-Lang." >&5
+echo "$as_me: WARNING: Rejecting system S-Lang with UTF-8 support. It is incompatible with DOSEMU. Using supplied S-Lang." >&2;}
+    ./mkpluginhooks enable slang yes
+else
+  echo "$as_me:$LINENO: checking for SLtt_get_terminfo in -lslang" >&5
 echo $ECHO_N "checking for SLtt_get_terminfo in -lslang... $ECHO_C" >&6
 if test "${ac_cv_lib_slang_SLtt_get_terminfo+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lslang  $LIBS"
+LIBS="-lslang -lm -ldl $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -6525,19 +6583,15 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_slang_SLtt_get_terminfo" >&5
 echo "${ECHO_T}$ac_cv_lib_slang_SLtt_get_terminfo" >&6
 if test $ac_cv_lib_slang_SLtt_get_terminfo = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSLANG 1
-_ACEOF
-
-  LIBS="-lslang $LIBS"
-
+  LIBS="$LIBS -lslang -lm -ldl";LDFLAGS="$LDFLAGS $SLANGLIB"
 else
-  { { echo "$as_me:$LINENO: error: unable to compile.  install slang-devel or check config.log" >&5
-echo "$as_me: error: unable to compile.  install slang-devel or check config.log" >&2;}
-   { (exit 1); exit 1; }; }
+  { echo "$as_me:$LINENO: WARNING: No S-Lang library found. Using supplied S-Lang." >&5
+echo "$as_me: WARNING: No S-Lang library found. Using supplied S-Lang." >&2;}
+		./mkpluginhooks enable slang yes
 fi
 
-  LDFLAGS="$LDFLAGS $SLANGLIB"
+fi
+
 
 fi;
 
@@ -8325,7 +8379,7 @@ INCDIR="-I\${SRCPATH}/plugin/include -I\${SRCPATH}/include ${SLANGINC}"
 
 CFLAGS="-Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -Wpointer-arith"
 if test "$dodebug" = "yes"; then
-  CFLAGS="$CFLAGS -g"
+  CFLAGS="$CFLAGS -gstabs+"
   cat >>confdefs.h <<\_ACEOF
 #define _DEBUG 1
 _ACEOF
