Added configure checks for bdftopcf and mkfontdir.
git-svn-id: https://dosemu.svn.sourceforge.net/svnroot/dosemu/trunk@1703 7758b857-130e-0410-ab9c-d8735a528d18

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -690,6 +690,8 @@ X_PRE_LIBS
 X_LIBS
 X_EXTRA_LIBS
 X_SUPPORT
+BDFTOPCF
+MKFONTDIR
 VERSION
 SUBLEVEL
 PATCHLEVEL1
@@ -10738,6 +10740,95 @@ fi
 
 
     fi
+
+    # Extract the first word of "bdftopcf", so it can be a program name with args.
+set dummy bdftopcf; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_BDFTOPCF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$BDFTOPCF"; then
+  ac_cv_prog_BDFTOPCF="$BDFTOPCF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_BDFTOPCF=""yes""
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_BDFTOPCF" && ac_cv_prog_BDFTOPCF=""no""
+fi
+fi
+BDFTOPCF=$ac_cv_prog_BDFTOPCF
+if test -n "$BDFTOPCF"; then
+  { echo "$as_me:$LINENO: result: $BDFTOPCF" >&5
+echo "${ECHO_T}$BDFTOPCF" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+    # Extract the first word of "mkfontdir", so it can be a program name with args.
+set dummy mkfontdir; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_MKFONTDIR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MKFONTDIR"; then
+  ac_cv_prog_MKFONTDIR="$MKFONTDIR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_MKFONTDIR=""yes""
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_MKFONTDIR" && ac_cv_prog_MKFONTDIR=""no""
+fi
+fi
+MKFONTDIR=$ac_cv_prog_MKFONTDIR
+if test -n "$MKFONTDIR"; then
+  { echo "$as_me:$LINENO: result: $MKFONTDIR" >&5
+echo "${ECHO_T}$MKFONTDIR" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+    if test "$MKFONTDIR" = "no" -o "$BDFTOPCF" = "no"; then
+        { { echo "$as_me:$LINENO: error:
+Your system doesn't seem to have bdftopcf or mkfontdir available.
+Please install these packages or a package named like 'xorg-x11-font-utils'
+or 'xfonts-utils' and retry." >&5
+echo "$as_me: error:
+Your system doesn't seem to have bdftopcf or mkfontdir available.
+Please install these packages or a package named like 'xorg-x11-font-utils'
+or 'xfonts-utils' and retry." >&2;}
+   { (exit 1); exit 1; }; }
+     fi
+
 else
   { echo "$as_me:$LINENO: Compiling without X support..." >&5
 echo "$as_me: Compiling without X support..." >&6;}
@@ -11961,12 +12052,12 @@ X_PRE_LIBS!$X_PRE_LIBS$ac_delim
 X_LIBS!$X_LIBS$ac_delim
 X_EXTRA_LIBS!$X_EXTRA_LIBS$ac_delim
 X_SUPPORT!$X_SUPPORT$ac_delim
+BDFTOPCF!$BDFTOPCF$ac_delim
+MKFONTDIR!$MKFONTDIR$ac_delim
 VERSION!$VERSION$ac_delim
 SUBLEVEL!$SUBLEVEL$ac_delim
 PATCHLEVEL1!$PATCHLEVEL1$ac_delim
 PATCHLEVEL2!$PATCHLEVEL2$ac_delim
-RELEASE_DATE!$RELEASE_DATE$ac_delim
-USE_MHPDBG!$USE_MHPDBG$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -12008,6 +12099,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+RELEASE_DATE!$RELEASE_DATE$ac_delim
+USE_MHPDBG!$USE_MHPDBG$ac_delim
 DEBUGGER!$DEBUGGER$ac_delim
 subdirs!$subdirs$ac_delim
 ASPI_SUPPORT!$ASPI_SUPPORT$ac_delim
@@ -12021,7 +12114,7 @@ ASM_PEDANTIC!$ASM_PEDANTIC$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 11; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 13; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
