2003/02/04 ver 1.1.4.11 unofficial pre-release
	From Stas
	- prevent IRQ conflicts and fix double registrations of the
	  keyboard IRQ in init.c and serv_8042.c.
	From Bart
	- (and Stas) fix comcom problem when environment segment == 0
	- small Makefile cleanups; include only necessary dependency files
	- remove all traces of $_secure, $_odd_hosts and $_diskless_hosts
	  since by default any remote hosts will get root privileges
	  dropped and diskless host security can be managed via sudo.
	- re-add SLang library, but now updated to version 1.4.8, as a
	  plugin, in stripped down source code form, to avoid problems 
	  with the utf-8 enabled default SLang library that various 
	  distributions ship.
	- adjustments to dosemu script: do not silently write to
	  ~/.dosemurc, run with /bin/sh instead of /bin/bash and only
	  write $_hdimage to ~/.dosemurc for system-wide installations.
	  Also adjust "-install" to be able to take no parameters (which
	  reinstalls FreeDOS).
	- quit DOSEMU (via the sigchld handler) if the port server is
	  killed.
	- remove config.usesX setting and any usage of it. It was only set 
	  by the -Y and -Z options which seem to have been unused since
	  1995.
	- fix for current_iopl in priv.c (misbehaviour spotted by Reinhard
	  Karcher)
	- don't open /dev/gpmdata-style mice in terminal mode. They don't
	  work then.
	- Made the portserver synchronous for port writes -- DOSEMU waits
	  for an acknowledgement. This already naturally happened for reads.
	- use the XFree86 video mode extension if available to switch 
	  resolutions for fullscreen X.
	- the X mouse cursor is now always invisible if mouse grab is active.
	- center text modes for fullscreen X.
	- (with help from Stas) don't pass the ctrl-alt-f keycode to DOS
	  apps when fullscreen is toggled. Enable mouse grab automatically 
	  for fullscreen X in graphics mode if the X mouse cursor is
	  invisible. Move fullscreen and mouse grab toggle code to 
	  seperate functions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6467,6 +6467,8 @@ echo $ECHO_N "checking for S-Lang... $ECHO_C" >&6
       SLANGLIB="-L${withval}/lib"
     fi
   fi
+    echo "$as_me:$LINENO: result: $SLANGINC $SLANGLIB" >&5
+echo "${ECHO_T}$SLANGINC $SLANGLIB" >&6
 
 echo "$as_me:$LINENO: checking for SLtt_get_terminfo in -lslang" >&5
 echo $ECHO_N "checking for SLtt_get_terminfo in -lslang... $ECHO_C" >&6
@@ -8021,6 +8023,57 @@ fi
 
 fi
 
+echo "$as_me:$LINENO: checking for X11/extensions/xf86vmode.h" >&5
+echo $ECHO_N "checking for X11/extensions/xf86vmode.h... $ECHO_C" >&6
+if test "${ac_cv_header_X11_extensions_xf86vmode_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <X11/Xlib.h>
+
+#include <X11/extensions/xf86vmode.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_X11_extensions_xf86vmode_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_header_X11_extensions_xf86vmode_h=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_X11_extensions_xf86vmode_h" >&5
+echo "${ECHO_T}$ac_cv_header_X11_extensions_xf86vmode_h" >&6
+if test $ac_cv_header_X11_extensions_xf86vmode_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_XVIDMODE 1
+_ACEOF
+ LIBS="-lXxf86vm $LIBS"
+else
+  { echo "$as_me:$LINENO: checking Compiling without the XF86 video mode extension" >&5
+echo "$as_me: checking Compiling without the XF86 video mode extension" >&6;}
+fi
+
+
+
 PACKAGE_VERSION=`cat VERSION`
 VV=$PACKAGE_VERSION
 VERSION=${VV%%.*}
@@ -8451,6 +8504,9 @@ CPPFLAGS="${CPPFLAGS} -MMD ${INCDIR}"
 
 
           ac_config_files="$ac_config_files Makefile.conf"
+
+
+
 
 
 
