Remove the S-Lang plugin. DOSEMU now cooperates nicely with all SLang libraries that are present in Linux distributions, so it is no longer necessary. Made a comment about some minor issues with the various library versions in existence. If no slang-devel library is installed, DOSEMU can now compile without terminal support.
git-svn-id: https://dosemu.svn.sourceforge.net/svnroot/dosemu/trunk@1044 7758b857-130e-0410-ab9c-d8735a528d18

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7518,49 +7518,182 @@ fi
 # Check whether --with-slangdir or --without-slangdir was given.
 if test "${with_slangdir+set}" = set; then
   withval="$with_slangdir"
-  echo "$as_me:$LINENO: checking for S-Lang" >&5
+
+fi;
+echo "$as_me:$LINENO: checking for S-Lang" >&5
 echo $ECHO_N "checking for S-Lang... $ECHO_C" >&6
-  SLANGINC=""
-  if test "$withval" = "src/plugin/slang"; then
-    $srcdir/mkpluginhooks enable slang yes
-  elif test "$withval" = "default"; then
-    if test -d $srcdir/../slang; then
-      SLANGINC="-I ${srcdir}/../slang/src"
-      SLANGLIB="-L ${srcdir}/../slang/src/objs"
-    else
-      if test -d $prefix/include/slang; then
-        SLANGINC="-I${prefix}/include/slang"
-      elif test -d /usr/include/slang; then
-        SLANGINC="-I/usr/include/slang"
-      fi
-    fi
+SLANGINC=""
+if test "$with_slangdir" = ""; then
+  if test -d $srcdir/../slang; then
+    SLANGINC="-I ${srcdir}/../slang/src"
+    SLANGLIB="-L ${srcdir}/../slang/src/objs"
   else
-        if test -f $withval/src/slang.h; then
-      SLANGINC="-I${withval}/src"
-      SLANGLIB="-L${withval}/src/objs"
-    else
-            if test -d $withval/include/slang; then
-        SLANGINC="-I${withval}/include/slang"
-      elif test -d $withval/include; then
-        SLANGINC="-I${withval}/include"
-      fi
-      SLANGLIB="-L${withval}/lib"
+    if test -d $prefix/include/slang; then
+      SLANGINC="-I${prefix}/include/slang"
+    elif test -d /usr/include/slang; then
+      SLANGINC="-I/usr/include/slang"
     fi
   fi
-    if test "$withval" = "src/plugin/slang"; then
-   LIBS="$LIBS -lm -ldl"
-   echo "$as_me:$LINENO: result: " >&5
-echo "${ECHO_T}" >&6
+else
+    if test -f $with_slangdir/src/slang.h; then
+    SLANGINC="-I${with_slangdir}/src"
+    SLANGLIB="-L${with_slangdir}/src/objs"
   else
-   echo "$as_me:$LINENO: result: $SLANGINC $SLANGLIB" >&5
+        if test -d $with_slangdir/include/slang; then
+      SLANGINC="-I${with_slangdir}/include/slang"
+    elif test -d $with_slangdir/include; then
+      SLANGINC="-I${with_slangdir}/include"
+    fi
+    SLANGLIB="-L${with_slangdir}/lib"
+  fi
+fi
+CPPFLAGS="$SLANGINC"
+echo "$as_me:$LINENO: result: $SLANGINC $SLANGLIB" >&5
 echo "${ECHO_T}$SLANGINC $SLANGLIB" >&6
-   echo "$as_me:$LINENO: checking for SLtt_get_terminfo in -lslang" >&5
+if test "${ac_cv_header_slang_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for slang.h" >&5
+echo $ECHO_N "checking for slang.h... $ECHO_C" >&6
+if test "${ac_cv_header_slang_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_slang_h" >&5
+echo "${ECHO_T}$ac_cv_header_slang_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking slang.h usability" >&5
+echo $ECHO_N "checking slang.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <slang.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking slang.h presence" >&5
+echo $ECHO_N "checking slang.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <slang.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: slang.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: slang.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: slang.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: slang.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: slang.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: slang.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: slang.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: slang.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: slang.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: slang.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: slang.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: slang.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: slang.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: slang.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: slang.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: slang.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for slang.h" >&5
+echo $ECHO_N "checking for slang.h... $ECHO_C" >&6
+if test "${ac_cv_header_slang_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_slang_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_slang_h" >&5
+echo "${ECHO_T}$ac_cv_header_slang_h" >&6
+
+fi
+if test $ac_cv_header_slang_h = yes; then
+  echo "$as_me:$LINENO: checking for SLtt_get_terminfo in -lslang" >&5
 echo $ECHO_N "checking for SLtt_get_terminfo in -lslang... $ECHO_C" >&6
 if test "${ac_cv_lib_slang_SLtt_get_terminfo+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lslang -lm -ldl $LIBS"
+LIBS="-lslang  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -7618,16 +7751,28 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_slang_SLtt_get_terminfo" >&5
 echo "${ECHO_T}$ac_cv_lib_slang_SLtt_get_terminfo" >&6
 if test $ac_cv_lib_slang_SLtt_get_terminfo = yes; then
-  LIBS="$LIBS -lslang -lm -ldl";LDFLAGS="$LDFLAGS $SLANGLIB"
+  { echo "$as_me:$LINENO: Compiling with S-Lang support..." >&5
+echo "$as_me: Compiling with S-Lang support..." >&6;}
+    cat >>confdefs.h <<\_ACEOF
+#define USE_SLANG 1
+_ACEOF
+
+    LIBS="$LIBS -lslang -lm -ldl";LDFLAGS="$LDFLAGS $SLANGLIB"
 else
-  { echo "$as_me:$LINENO: WARNING: No S-Lang library found. Using supplied S-Lang." >&5
-echo "$as_me: WARNING: No S-Lang library found. Using supplied S-Lang." >&2;}
-		$srcdir/mkpluginhooks enable slang yes
+  { echo "$as_me:$LINENO: WARNING: No S-Lang library found." >&5
+echo "$as_me: WARNING: No S-Lang library found." >&2;}
+    $srcdir/mkpluginhooks enable term no
+
 fi
 
-  fi
+else
+  { echo "$as_me:$LINENO: WARNING: No S-Lang header file found." >&5
+echo "$as_me: WARNING: No S-Lang header file found." >&2;}
+  $srcdir/mkpluginhooks enable term no
 
-fi;
+fi
+
+
 
 
 if test "x$ac_path_x_has_been_run" != xyes; then
@@ -9011,7 +9156,7 @@ fi
 
 if test "$have_x" = "yes" ; then
   LDFLAGS="$LDFLAGS $X_LIBS"
-  CPPFLAGS="$X_CFLAGS"
+  CPPFLAGS="$CPPFLAGS $X_CFLAGS"
 
 
 echo "$as_me:$LINENO: checking for XOpenDisplay in -lX11" >&5
@@ -9643,7 +9788,7 @@ fi
 
 
 
-INCDIR="-I\${top_builddir}/src/include -I\${top_builddir}/src/plugin/include ${SLANGINC}"
+INCDIR="-I\${top_builddir}/src/include -I\${top_builddir}/src/plugin/include"
 
 
 CFLAGS="-Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs"
@@ -9853,6 +9998,9 @@ CPPFLAGS="${CPPFLAGS} -MMD \${INCDIR}"
 
 
           ac_config_commands="$ac_config_commands Makefile"
+
+
+
 
 
 
