Check for the existence of the Xxf86vm and Xext libraries, not just header files. Adjust INSTALL instructions.
git-svn-id: https://dosemu.svn.sourceforge.net/svnroot/dosemu/trunk@1763 7758b857-130e-0410-ab9c-d8735a528d18

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8384,6 +8384,10 @@ fi
 fi
 
 if test "$have_x" = "yes" ; then
+
+    SLIBS=$LIBS
+    LIBS="$LIBS $X_LIBS"
+
     { echo "$as_me:$LINENO: Compiling with X support..." >&5
 echo "$as_me: Compiling with X support..." >&6;}
     cat >>confdefs.h <<\_ACEOF
@@ -8400,6 +8404,75 @@ if test "${enable_mitshm+set}" = set; then
 fi
 
 
+    if test "$enable_mitshm" != "no" ; then
+      { echo "$as_me:$LINENO: checking for XShmPutImage in -lXext" >&5
+echo $ECHO_N "checking for XShmPutImage in -lXext... $ECHO_C" >&6; }
+if test "${ac_cv_lib_Xext_XShmPutImage+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXext  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char XShmPutImage ();
+int
+main ()
+{
+return XShmPutImage ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_Xext_XShmPutImage=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_Xext_XShmPutImage=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_Xext_XShmPutImage" >&5
+echo "${ECHO_T}$ac_cv_lib_Xext_XShmPutImage" >&6; }
+if test $ac_cv_lib_Xext_XShmPutImage = yes; then
+  enable_mitshm="yes"
+else
+  enable_mitshm="no"
+fi
+
+    fi
     if test "$enable_mitshm" != "no" ; then
       { echo "$as_me:$LINENO: checking for X11/extensions/XShm.h" >&5
 echo $ECHO_N "checking for X11/extensions/XShm.h... $ECHO_C" >&6; }
@@ -8463,6 +8536,75 @@ if test "${enable_vidmode+set}" = set; then
   enableval=$enable_vidmode;
 fi
 
+    if test "$enable_vidmode" != "no" ; then
+      { echo "$as_me:$LINENO: checking for XF86VidModeSwitchToMode in -lXxf86vm" >&5
+echo $ECHO_N "checking for XF86VidModeSwitchToMode in -lXxf86vm... $ECHO_C" >&6; }
+if test "${ac_cv_lib_Xxf86vm_XF86VidModeSwitchToMode+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXxf86vm  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char XF86VidModeSwitchToMode ();
+int
+main ()
+{
+return XF86VidModeSwitchToMode ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_Xxf86vm_XF86VidModeSwitchToMode=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_Xxf86vm_XF86VidModeSwitchToMode=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_Xxf86vm_XF86VidModeSwitchToMode" >&5
+echo "${ECHO_T}$ac_cv_lib_Xxf86vm_XF86VidModeSwitchToMode" >&6; }
+if test $ac_cv_lib_Xxf86vm_XF86VidModeSwitchToMode = yes; then
+  enable_vidmode="yes"
+else
+  enable_vidmode="no"
+fi
+
+    fi
     if test "$enable_vidmode" = "no"; then
                { echo "$as_me:$LINENO: Compiling without the XF86 video mode extension" >&5
 echo "$as_me: Compiling without the XF86 video mode extension" >&6;}
@@ -8523,6 +8665,9 @@ fi
 
 
     fi
+
+    LIBS=$SLIBS
+    unset SLIBS
 
     # Extract the first word of "bdftopcf", so it can be a program name with args.
 set dummy bdftopcf; ac_word=$2
