97/01/19 ver. 0.64.3 released
	From Hans
	- removed emumodule (don't need it any more;-)
	- cleaned up kernel dependencies
	- adapted ./configure and Makefiles
	- Made mouse functionable for win31-in-xdos (hiding X-cursor,
          calibrating win31 cursor)
	- little fix for xtermdos
	- Updated the docs
	From JES
	- basic mouse functionality for win31-in-xdos
	From Herbert Xu <herbert@greathan.apana.org.au>
	- additions to man/dos.1, man/xtermdos.1
96/12/30 ver. 0.64.2.2 released
	From Erik Mouw
	- sequencer emulator for VGAemu (compatible with Trident 8900)
	  This lets WIN31 run in xdos :-), ... but without mouse :-(
96/12/30 ver. 0.64.2.1 released
	From Hans
	- Finaly got expand-down-fake in DPMI work, so older DJGPP work again.
	  ( and maybe some games too )
	- Additional checks in ./configure for debian inconsistencies,
	  Forcing to ELF, if no GCC specs file available.
	- ... and this time did not forget to increase the version ;-)
	From Erik Mow
	- Additional checks in ./configure for bison installed
	From Grant R. Guenther <grant@knot.torque.net>
	( hey, Grant is the man who hacked the ZIP and other drives using
          dosemu, so he then could write the Linux drivers ;-)
	- "T" debug flag and LOG_IO macro
	From Bernd Paysan <paysan@informatik.tu-muenchen.de>
	- fixed the keycodes for AccelX
	- fix for micro timing problems, timer now strictly monotonous
	  ( Bernd's fix _really_ works great, Hans:-)
96/12/07 ver. 0.64.2 released
	From Hans:
	- vm86plus (2nd version) now is in the kernels >= 2.1.15
	  ( it took long, but we finaly succeeded, thanks Linus :-)
	- small adaptation and cleanup (docs, configure)
	- minor fixes for clean compile under various compile options
	- key-board fix for french keyboards (from Alain Knaff)
96/12/07 ver. 0.64.2-pre5 (privat release for JES only)
        From Hans:
	- vm86plus (emumodule), third round
	  ( Linus requested to put our stuff into a separate syscall )
	  kernel patches now for 2.0.27, 2.1.14
	- small fix for -F bug.
	- DPMI: tried to work around illegitime expand-down segments

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -80,17 +80,35 @@ dnl Here is where we do our stuff
 CONFIG_HOST=`uname -s`
 if test "$CONFIG_HOST" = "Linux"; then
   CONFIG_HOST='linux'
+  if test ! -f /usr/include/linux/version.h ; then
+    echo ''
+    echo '*** error:'
+    echo '*** Your system has no complete /usr/include/linux,'
+    echo '*** (version.h missing) ... giving up'
+    echo ''
+    exit 1
+  fi
+  force_vm86plus="1"
+else
+  force_vm86plus="0"
 fi
 AC_SUBST(CONFIG_HOST)
 
 dnl Do ELF if possible
 
- if grep __ELF__ `gcc -v 2>&1|head -n1|cut -d' ' -f4` /dev/null 1>/dev/null 2>&1; then 
-  ELF="ELF=1"
+ if ! gcc -v 2>&1|grep specs >/dev/null 2>&1; then
+   AC_MSG_WARN(Your GCC installation is incomplete: specs file is missing.)
+   AC_MSG_WARN(We assume your GCC compiles for ELF.)
+   AC_MSG_WARN( )
+   ELF="ELF=1"
  else
-# DON'T CHANGE THIS: this makes libdosemu start high enough to be safe.
-# should be okay at...0x20000000 for .5 GB mark.
-  LIBSTART="LIBSTART = 0x20000000"
+   if grep __ELF__ `gcc -v 2>&1|head -n1|cut -d' ' -f4` /dev/null 1>/dev/null 2>&1; then 
+    ELF="ELF=1"
+   else
+    # DON'T CHANGE THIS: this makes libdosemu start high enough to be safe.
+    # should be okay at...0x20000000 for .5 GB mark.
+    LIBSTART="LIBSTART = 0x20000000"
+   fi
  fi
  AC_SUBST(LIBSTART)
  AC_SUBST(ELF)
@@ -246,7 +264,7 @@ AC_SUBST(x_libraries)
 REALTOPDIR=`nolinks=1; pwd`
 VERSION="0"
 SUBLEVEL="64"
-PATCHLEVEL="1.0"
+PATCHLEVEL="3.0"
 THISVERSION="$VERSION.$SUBLEVEL.$PATCHLEVEL"
 EMUVER="VERSION.$SUBLEVEL"
 AC_DEFINE_UNQUOTED(EMUVER, "$EMUVER")
@@ -277,27 +295,19 @@ if test "$CONFIG_HOST" = "linux"; then
 dnl BOCHS
 dnl   AC_DEFINE_UNQUOTED(X86_EMULATOR_FLAGS)
 
-dnl Do Kernel builtin vm86plus
- AC_ARG_ENABLE(kernelvm86plus,
-               [  --enable-kernelvm86plus do compile for kernel builtin vm86plus support],
-               [kernelvm86plus="yes"],[kernelvm86plus="no"])
-  if test "$kernelvm86plus" = "yes"; then
-   AC_CHECKING("Compiling for kernel builtin vm86plus support");
-   AC_DEFINE_UNQUOTED(BUILTIN_VMP86PLUS)
-   BUILTIN_VMP86PLUS="-DBUILTIN_VMP86PLUS"
-   AC_SUBST(BUILTIN_VMP86PLUS)
-  else
-   AC_CHECKING("Compiling for normal vm86 kernels");
-  fi
-
 dnl Do vm86plus 
  AC_ARG_ENABLE(novm86plus,
                [  --enable-novm86plus     do NOT use VM86 enhancement],
-               [vm86plus="no"],[vm86plus="yes"])
-  if test "$kernelvm86plus" = "yes"; then
-    vm86plus="yes"
+               [novm86plus="yes"],[novm86plus="no"])
+  vm86plus="yes"
+  if test "$novm86plus" = "yes"; then
+    vm86plus="no"
   fi
+
   if test "$vm86plus" = "yes"; then
+   AC_DEFINE_UNQUOTED(BUILTIN_VMP86PLUS)
+   BUILTIN_VMP86PLUS="-DBUILTIN_VMP86PLUS"
+   AC_SUBST(BUILTIN_VMP86PLUS)
    AC_CHECKING("Compiling for vm86plus support");
    AC_DEFINE_UNQUOTED(REQUIRES_VM86PLUS)
    AC_DEFINE_UNQUOTED(USE_MHPDBG)
@@ -305,15 +315,8 @@ dnl Do vm86plus
    AC_SUBST(USE_MHPDBG)
    DEBUGGER="arch/$CONFIG_HOST/debugger"
    REQUIRES_VM86PLUS="YES"
-   if test "$kernelvm86plus" = "yes"; then
-     OPTIONALSUBDIRS="dosext/net/v-net arch/$CONFIG_HOST/emumod"
-     REQUIRED="tools commands tools/periph"
-   else
-     AC_CHECKING("Compiling emumodule");
-     OPTIONALSUBDIRS="dosext/net/v-net"
-     REQUIRED="tools commands tools/periph arch/$CONFIG_HOST/emumod"
-     emumodule="yes"
-   fi
+   OPTIONALSUBDIRS="dosext/net/v-net"
+   REQUIRED="tools commands tools/periph"
   else
    AC_CHECKING("Compiling without vm86plus support");
    DEBUGGER=""
@@ -321,20 +324,6 @@ dnl Do vm86plus
   fi
 fi
 AC_SUBST(DEBUGGER)
-
-dnl Do SMP compilation for modules
- AC_ARG_ENABLE(SMPmodules,
-               [  --enable-SMPmodules     do compile emumodule for SMP kernels],
-               [SMPmodules="yes"],[SMPmodules="no"])
-  if test "$emumodule" = "yes"; then
-    if test "$SMPmodules" = "yes"; then
-     AC_CHECKING("Compiling modules for SMP kernels");
-     SMP="-D__SMP__"
-     AC_SUBST(SMP)
-    else
-     AC_CHECKING("Compiling modules for uniprocessor kernels");
-    fi
-  fi
 
 dnl Do compilation for GDB
  AC_ARG_ENABLE(dodebug,
@@ -371,18 +360,11 @@ AC_SUBST(REQUIRES_VM86PLUS)
 
 dnl Now CFLAGS and INCLUDES
 
-#Change the following line if the right kernel includes reside elsewhere
-# LINUX_KERNEL = /usr/src/linux
-LINUX_KERNEL=`$SRCPATH/arch/$CONFIG_HOST/kversion.sh -find -print`
-LINUX_INCLUDE="$LINUX_KERNEL/include"
-AC_SUBST(LINUX_KERNEL)
-AC_SUBST(LINUX_INCLUDE)
-
 # does this work if you do make -C <some dir>
 TOPDIR=`nolinks=1;pwd`
 AC_SUBST(TOPDIR)
 
-INCDIR="-I${SRCPATH}/include  -I${LINUX_INCLUDE} -I${SRCPATH}/base/dev/pic -I${SRCPATH}/dosext/dpmi ${XINCLUDES}"
+INCDIR="-I${SRCPATH}/include -I${SRCPATH}/base/dev/pic -I${SRCPATH}/dosext/dpmi ${XINCLUDES}"
 AC_SUBST(INCDIR)
 
 if test "$dodebug" = "yes"; then
@@ -452,7 +434,6 @@ src/arch/linux/Makefile.main
 src/arch/linux/async/Makefile
 src/arch/linux/debugger/Makefile
 src/arch/linux/dosext/sound/Makefile
-src/arch/linux/emumod/Makefile
 src/base/async/Makefile
 src/base/bios/Makefile
 src/base/dev/dma/Makefile
@@ -499,6 +480,16 @@ if test ! "$AS86" = "as86" -a ! "$LD86" = "ld86" ; then
   AC_MSG_WARN(Your system doesn't seem to have as86 and/or ld86.)
   AC_MSG_WARN(These programs are required to assemble the Dosemu)
   AC_MSG_WARN(BIOS. Please install them.)
+  AC_MSG_WARN( )
+fi
+
+dnl The bison problem
+if test -z "`echo $YACC | grep bison`" ; then
+  AC_MSG_WARN( )
+  AC_MSG_WARN(Your system doesn't seem to have bison available.)
+  AC_MSG_WARN(There have been reports that bison is really required to)
+  AC_MSG_WARN(compile Dosemu. You may try to use $YACC instead, your)
+  AC_MSG_WARN(mileage may vary. If you want to be sure, install bison.)
   AC_MSG_WARN( )
 fi
 
