97/03/07 ver. 0.65.99.15 unofficial pre-release
	From Alberto
	- cleanup for CFLAGS in configure(.in)
	- corrections in etc/config.dist
	- missing exception 16 handling in src/arch/linux/async/sigsegv.c
	- various fixes in src/base/async/int.c, temp fix for Ctrl-C bug
	  in Djgpp (int 23 revectored and caputered).
	- changed 0/1 to REVECT/NO_REVECT
	- cleanup of usage message in src/base/init/config.c
	  and fix wrong cardtype number
	- fixes to buffered debug out (log_printf).
	- mouse fix (serial/int14.c)
	- fixed 'hlt' optimization in run_dpmi()
	- cleaned up 'case 1..2:' to 'case 1: case 2:' in various places
	- in_dos_21 warnings fixed
	- some mfs fixes.
	From Thomas Winder <thomas.winder@sea.ericsson.se>
	- struct sigaction fixes for glibc-2 in src/arch/linux/async/signal.c
	From Hans
	- fix for default-configure
	- made 'irqpassing' a synonym for 'sillyint', because users
	  apparently get confused. Also adapted config.dist

diff --git a/default-configure b/default-configure
--- a/default-configure
+++ b/default-configure
@@ -6,6 +6,11 @@ if [ "$1" != "" ]; then
   CONF_FILE=$1
 fi
 
+if [ ! -f $CONF_FILE ]; then
+  echo "$CONF_FILE cannot be opened"
+  exit 1
+fi
+
 set `cut '-d{' -f2 $CONF_FILE |cut '-d}' -f1`
 
 #echo "$*"
@@ -17,7 +22,7 @@ while [ "$1" != "" ]; do
 
   case "$1" in
     novm86plus)
-      if [ "$2" = "on" ]; then STRING="$STRING --enable-nomitshm"; fi
+      if [ "$2" = "on" ]; then STRING="$STRING --enable-novm86plus"; fi
       ;;
     dodebug)
       if [ "$2" = "on" ]; then STRING="$STRING --enable-dodebug"; fi
