97/04/30 ver. 0.67.0.1 unofficial pre-release
	From Hans
	- further enhancements to DEXE stuff
	  - hdimages containing DEXE get a magic "\x0eDEXE"
	  - configuration is now (hidden from file access) put into
	    cylinder 0 (behind the MBR)
	  - dosemu now handles DEXE loading itself ( option -L)
	    a 'dosexec' sym-linked dos sets -L option (like xdos does -X)
	  - a DEXEs hdimage is always drive C, if not explicitle allowed
	    via 'dexe { allowdisk }', no other disk will be available
	    even if defined in /etc/dosemu.conf
	  - Option -F is forbidden for DEXE, so the security settings
	    in /etc/dosemu.conf can't be disabled.
	  - 'secure on' can be forced in /etc/dosemu.conf for DEXE,
	    even if 'off' otherwise.
	  - 'dexe { forcexdos }' forces xdos, when DEXE is run on X.
	    This can be included in DEXE-configurations, when the
	    application requires graphics and would bomb on Slang otherwise.
	  - New tool: src/tools/periph/dexeconfig, which inserts/extracts
	    the configuration file from a DEXE
	  - updated dexe/mkdexe to reflect the changes

diff --git a/dexe/mkdexe b/dexe/mkdexe
--- a/dexe/mkdexe
+++ b/dexe/mkdexe
@@ -96,14 +96,15 @@ function copy_text_file {
     $editor ${TMP}/$1
   fi
   if [ -f ${TMP}/$1 ]; then
-    docrlf=""
-    if [ "$1" != "dconfig" ]; then docrlf="-t";fi
-    if ! ${MYDIR}/do_mtools $APP_HDIMAGE mcopy -o $docrlf ${TMP}/$1 W:/${1}; then
-      echo "XXXX error during mcopy of $1 XXXX"
-      echo "may be you choose the size of the hdimage too small"
-      exit 1
-    fi 
-
+    if [ "$1" = "dconfig" ]; then
+      $DEXECONF -M -i ${TMP}/$1 $APP_HDIMAGE
+    else
+      if ! ${MYDIR}/do_mtools $APP_HDIMAGE mcopy -o -t ${TMP}/$1 W:/${1}; then
+        echo "XXXX error during mcopy of $1 XXXX"
+        echo "may be you choose the size of the hdimage too small"
+        exit 1
+      fi 
+    fi
   fi
 }
 
@@ -114,6 +115,7 @@ fi
 DDIR=`(cd ..; pwd -P)`
 MYDIR=`pwd -P`
 MKFAT=${DDIR}/src/tools/periph/mkfatimage16
+DEXECONF=${DDIR}/src/tools/periph/dexeconfig
 
 TARGDIR="/var/lib/dosemu"
 mkdir -p $TARGDIR
@@ -280,6 +282,8 @@ copy_text_file config.sys $_CONFIRM $CONFSYS
 
 copy_text_file autoexec.bat $CONFIRM $AUTOEXEC
 
+# make it executable
+chmod 755 $APP_HDIMAGE
 
 # we cleanup things
 rm -rf $TMP
